### ISSUE TITLE
AttributeError: 'mpi4py.MPI.Intracomm' object has no attribute 'PingpongSR25'

### ISSUE THREAD

**Issue by jgphpc** [hpcugent/mympingpong#11]
Hi,

Trying to run mympingpong.py on a Cray, i get:
`srun -t2 -n2 ./bin/mympingpong.py -f /scratch/daint/piccinal -i 200 -n 200`

```
ERROR:root:Found none NUMANode for child path /topology/object/object[1]/object/object[7]/object/object/object[1]

Traceback (most recent call last):
  File "/apps/common/UES/sandbox/jgp/mympingpong.git/./bin/mympingpong.py", line 433, in <module>
    msgsize=go.options.messagesize, maxruntime=go.options.maxruntime)
  File "/apps/common/UES/sandbox/jgp/mympingpong.git/./bin/mympingpong.py", line 266, in run
    msgsize=go.options.messagesize, maxruntime=go.options.maxruntime)
  File "/apps/common/UES/sandbox/jgp/mympingpong.git/./bin/mympingpong.py", line 266, in run
    timingdata, group = self.pingpong(pair[0], pair[1], pmode=pmode, dat=dattosend)
  File "/apps/common/UES/sandbox/jgp/mympingpong.git/./bin/mympingpong.py", line 334, in pingpong
    timingdata, group = self.pingpong(pair[0], pair[1], pmode=pmode, dat=dattosend)
  File "/apps/common/UES/sandbox/jgp/mympingpong.git/./bin/mympingpong.py", line 332, in pingpong
    pp = PingPongSR.pingpongfactory('SR' + pmode, self.comm, p2, self.log)
    pp = PingPongSR.pingpongfactory('RS' + pmode, self.comm, p1, self.log)
  File "build/bdist.linux-x86_64/egg/vsc/mympingpong/pingpongers.py", line 73, in pingpongfactory
  File "build/bdist.linux-x86_64/egg/vsc/mympingpong/pingpongers.py", line 73, in pingpongfactory
  File "build/bdist.linux-x86_64/egg/vsc/mympingpong/pingpongers.py", line 63, in __init__
  File "build/bdist.linux-x86_64/egg/vsc/mympingpong/pingpongers.py", line 63, in __init__
  File "build/bdist.linux-x86_64/egg/vsc/mympingpong/pingpongers.py", line 208, in setsr
  File "build/bdist.linux-x86_64/egg/vsc/mympingpong/pingpongers.py", line 198, in setsr
AttributeError: 'mpi4py.MPI.Intracomm' object has no attribute 'PingpongSR25'
AttributeError: 'mpi4py.MPI.Intracomm' object has no attribute 'PingpongSR25'
srun: error: nid00166: tasks 0-1: Exited with exit code 1
srun: Terminating job step 419182.3
```

I am using mpi4py==1.3.1 + Python/2.7.12.
It looks like PingpongSR25 is defined in https://github.com/hpcugent/mympingpong/blob/master/manual/pingpong_general_fixed_unroll.pyx.patch

Does it mean i need to reinstall mpi4py ?
Can you send instructions please ?

jg.
manual/pingpong_general_fixed_unroll.pyx.patch

**Comment by stdweird** [comment]
@jgphpc yes, you need to patch mpi4py and recompile it. we strongly recommend to use easybuild for this (and all your other software :smile: )

https://github.com/hpcugent/easybuild
@boegel any pointers wrt EB builds?

**Comment by stdweird** [comment]
looks like we still kept these around: https://github.com/hpcugent/mympingpong/blob/master/manual/instructions

**Comment by stdweird** [comment]
@jgphpc https://github.com/hpcugent/mympingpong/commit/7b40e68765ed084c3a1ff380728c0727414c790d
but not tested and not supported. we strongly advise to use EB

**Comment by boegel** [comment]
Latest EasyBuild release includes an easyconfig for the patched mpi4py, see https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/m/mpi4py/mpi4py-1.3.1-intel-2016a-Python-2.7.11-timed-pingpong.eb, which uses the patch https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/m/mpi4py/mpi4py-1.3.1_timed-pingpong.patch.

It should be straightforward to port that to your toolchain & Python version of choice (especially since @jgphpc knows his way around EasyBuild already).

**Comment by stdweird** [comment]
@jgphpc in that case you might want to wait till @wpoely86 has an easyconfig for the latest release

**Comment by wpoely86** [comment]
@jgphpc A new release of mympingpong is tagged and the corresponding easyconfigs can be found at hpcugent/easybuild-easyconfigs#3442

**Comment by jgphpc** [comment]
@wpoely86 

Hi,
I installed mympingpong/0.7.1-CrayGNU-2016.06-Python-2.7.12 on the Cray and i can produce the hdf5 file with `srun -t1 -n2 mympingpong -f $SCRATCH -i 200 -n 200` but i now have an issue with 
- srun -t5 -n1 mympingponganalysis -f PPnid00064-002-msg0001024B-nr00200-it00200-20161014-163338.h5 

because it fails in:

```
  File "/apps/brisi/UES/6.0.UP01/broadwell/easybuild/software/mympingpong/0.7.1-CrayGNU-2016.06-Python-2.7.12/lib/python2.7/site-packages/mympingpong-0.7.1-py2.7.egg/EGG-INFO/scripts/mympingponganalysis", line 310, in <module>

  File "/apps/brisi/UES/6.0.UP01/broadwell/easybuild/software/mympingpong/0.7.1-CrayGNU-2016.06-Python-2.7.12/lib/python2.7/site-packages/mympingpong-0.7.1-py2.7.egg/EGG-INFO/scripts/mympingponganalysis", line 254, in plot

  File "/apps/brisi/UES/6.0.UP01/broadwell/easybuild/software/Python/2.7.12-CrayGNU-2016.06/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/apps/brisi/UES/6.0.UP01/broadwell/easybuild/software/Python/2.7.12-CrayGNU-2016.06/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/apps/brisi/UES/6.0.UP01/broadwell/easybuild/software/Python/2.7.12-CrayGNU-2016.06/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/apps/brisi/UES/6.0.UP01/broadwell/easybuild/software/Python/2.7.12-CrayGNU-2016.06/lib/python2.7/lib-tk/Tkinter.py", line 1815, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:11.0"
```

Is there a way to build mympingponganalysis without mpi so i could run it on the login node instead of the compute node ?

jg.

**Comment by jgphpc** [comment]
continue on https://github.com/hpcugent/mympingpong/issues/14
